config/routes.rb
Rails.application.routes.draw do
  root 'students/lessons#index'
  devise_for :teachers, controllers: {
    sessions: 'teachers/sessions',
    passwords: 'teachers/passwords',
    registrations: 'teachers/registrations',
  }

  devise_scope :teacher do
    post 'teachers/guest_sign_in', to: 'teachers/sessions#new_guest'
  end

  namespace :teachers do
    resources :lessons, only: [:index, :new, :show, :edit, :create, :update]
    resources :area_classes, only: [:index, :create, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :courses, only: [:index, :create, :edit, :update, :destroy]
    resources :time_classes, only: [:index, :create, :edit, :update, :destroy]
    resources :attendees, only: [:create, :destroy, :index, :edit, :update]
    resources :students, only: [:index, :show, :edit, :update]
    resources :no_lessons, only: [:index, :create, :destroy]
    # get 'search/' => 'search#search', as: 'search'
  end
  get 'teachers/index'

  devise_for :students, controllers: {
    sessions: 'students/sessions',
    passwords: 'students/passwords',
    registrations: 'students/registrations',
  }

  devise_scope :student do
    post 'students/guest_sign_in', to: 'students/sessions#new_guest'
  end

  namespace :students do
    resources :lessons, only: [:index, :show]
    resources :attendees, only: [:index, :show, :create]
    resources :requests, only: [:show, :create]
  end
  resources :students, only: [:show, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  # 外部キーは空白だとNG、データは絶対必要。でも↓のオプションはデータなくてもいいよ、というおまじない。
  belongs_to :area_class, optional: true
  belongs_to :teacher, optional: true
  belongs_to :genre, optional: true
  belongs_to :time_class, optional: true
  has_many :attendees
  has_many :no_lessons
  attachment :image
  validates :area_class_id, presence: true
  validates :genre_id, presence: true
  validates :time_class_id, presence: true
  validates :teacher_id, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lesonns
  has_many :students

  validates :last_name, presence: true
  validates :sub_last_name, presence: true
  validates :first_name, presence: true
  validates :sub_first_name, presence: true
  validates :email, presence: true

  def self.guest
    find_or_create_by!(last_name: '先生', first_name: '太郎', sub_last_name: 'センセイ', sub_first_name: 'タロウ', email: 'guest_teacher@example.com') do |teacher|
      teacher.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
end

app/controllers/students/lessons_controller.rb
class Students::LessonsController < ApplicationController
  def index
    @lessons = Lesson.all
    @no_lessons = NoLesson.all.order(created_at: :desc)
  end

  def show
    @student = current_student
    @lesson = Lesson.find(params[:id])
    @no_lessons = NoLesson.all.order(created_at: :desc)
    @attendee = Attendee.new
  end
end

app/controllers/teachers/area_classes_controller.rb
class Teachers::AreaClassesController < ApplicationController
  before_action :authenticate_teacher!

  def index
    @area_class = AreaClass.new
    @area_classes = AreaClass.all
  end

  def create
    @area_class = AreaClass.new(area_class_params)
    @area_classes = AreaClass.all
    if @area_class.save
      redirect_to teachers_area_classes_path
    else
      render :index
    end
  end

  def edit
    @area_class = AreaClass.find(params[:id])
  end

  def update
    @area_class = AreaClass.find(params[:id])
    if @area_class.update(area_class_params)
      flash[:success] = "更新完了"
      redirect_to teachers_area_classes_path
    else
      render :edit
    end
  end

  # def destroy
  # @area_class = AreaClass.find(params[:id])
  # @area_class.destroy
  # redirect_to teachers_area_classes_path
  # end

  private

  def area_class_params
    params.require(:area_class).permit(:name)
  end
end

app/controllers/teachers/attendees_controller.rb
class Teachers::AttendeesController < ApplicationController
  before_action :authenticate_teacher!

  # def create
    # @attendee = Attendee.find_by(id: params[:id])
    # @attendee.save
  # end

  def index
    @attendee = Attendee.find_by(id: params[:id])
    @attendees = Attendee.all.order(created_at: :desc).search(params[:search])
    # @attendees = Attendee.where("created_at >= ?", Time.zone.now.beginning_of_day)
  end

  def edit
    @attendee = Attendee.find_by(id: params[:id])
  end

  def update
    @attendee = Attendee.find(params[:id])
    @attendee.update(attendee_params)
    flash[:success] = "更新完了"
    redirect_to teachers_attendees_path
  end

  private

  def attendee_params
    params.require(:attendee).permit(:attendance_status)
  end
end

app/controllers/teachers/confirmations_controller.rb
# frozen_string_literal: true

class Teachers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/teachers/courses_controller.rb
class Teachers::CoursesController < ApplicationController
  before_action :authenticate_teacher!

  def index
    @course = Course.new
    @courses = Course.all
  end

  def create
    @course = Course.new(course_params)
    @courses = Course.all
    if @course.save
      redirect_to teachers_courses_path
    else
      render :index
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
      flash[:success] = "更新完了"
      redirect_to teachers_courses_path
    else
      render :edit
    end
  end

  # def destroy
  # @course = Course.find(params[:id])
  # @course.destroy
  # redirect_to teachers_courses_path
  # end

  private

  def course_params
    params.require(:course).permit(:name)
  end
end

app/controllers/teachers/genres_controller.rb
class Teachers::GenresController < ApplicationController
  before_action :authenticate_teacher!

  def index
    @genre = Genre.new
    @genres = Genre.all
 end

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    if @genre.save
      redirect_to teachers_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:success] = "更新完了"
      redirect_to teachers_genres_path
    else
      render :edit
    end
  end

  # def destroy
  # @genre = Genre.find(params[:id])
  # @genre.destroy
  # redirect_to teachers_genres_path
  # end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/teachers/lessons_controller.rb
class Teachers::LessonsController < ApplicationController
  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      redirect_to teachers_lessons_path
    else
      render :new
    end
  end

  def index
    @lessons = Lesson.all
  end

  def show
    @lesson = Lesson.find(params[:id])
    @no_lesson = NoLesson.new
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      flash[:success] = "レッスン情報更新完了"
      redirect_to teachers_lessons_path
    else
      render :edit
    end
  end

  private

  def lesson_params
    params.require(:lesson).permit(:area_class_id, :genre_id, :teacher_id, :time_class_id, :image)
  end
end

app/controllers/teachers/no_lessons_controller.rb
class Teachers::NoLessonsController < ApplicationController
  before_action :authenticate_teacher!

  def index
    @no_lessons = NoLesson.all.order(created_at: :desc)
  end

  def create
    @no_lesson = NoLesson.new(no_lesson_params)
    @no_lesson.save
    flash[:success] = "休講登録完了しました"
    redirect_to teachers_no_lessons_path
  end

  def destroy
    @no_lesson = NoLesson.find(params[:id])
    @no_lesson.destroy
    redirect_to teachers_no_lessons_path
  end

  def no_lesson_params
    params.require(:no_lesson).permit(:lesson_id, :no_lesson_date)
  end
end

app/controllers/teachers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Teachers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/teachers/passwords_controller.rb
# frozen_string_literal: true

class Teachers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/teachers/registrations_controller.rb
# frozen_string_literal: true

class Teachers::RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource)
    teachers_lessons_path
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/teachers/search_controller.rb
class Teachers::SearchController < ApplicationController
  before_action :authenticate_teacher!

  def search
  	# @column = params["search"]["column"]
      # if search
      # Student.where(['content LIKE ?', "%#{search}%"])
      # else
      # Student.all
      # end
    end
end

app/controllers/teachers/sessions_controller.rb
# frozen_string_literal: true

class Teachers::SessionsController < Devise::SessionsController
  # ログイン後に遷移するpathを設定
  def after_sign_in_path_for(resource)
    teachers_attendees_path
  end

  # ログアウト後に遷移するpathを設定
  def after_sign_out_path_for(resource)
    new_teacher_session_path
  end

  def new_guest
    teacher = Teacher.guest
    sign_in teacher
    flash[:notice] = "ゲストユーザー(先生)としてログインしました。"
    redirect_to teachers_attendees_path
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/teachers/students_controller.rb
class Teachers::StudentsController < ApplicationController
  before_action :authenticate_teacher!

  def index
    @students = Student.all
  end

  def show
    @student = Student.find_by(id: params[:id])
  end

  # def search
  # Viewのformで取得したパラメータをモデルに渡す
  # @students = Student.search(id: params[:search])
  # end

  def edit
    @student = Student.find_by(id: params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    flash[:success] = "生徒情報更新完了"
    redirect_to teachers_students_path
  end

  private

  def student_params
    params.require(:student).permit(:teacher_id, :course_id)
  end
end

app/controllers/teachers/time_classes_controller.rb
class Teachers::TimeClassesController < ApplicationController
  before_action :authenticate_teacher!

  def index
    @time_class = TimeClass.new
    @time_classes = TimeClass.all
  end

  def create
    @time_class = TimeClass.new(time_class_params)
    @time_classes = TimeClass.all
    if @time_class.save
      redirect_to teachers_time_classes_path
    else
      render :index
    end
  end

  def edit
    @time_class = TimeClass.find(params[:id])
  end

  def update
    @time_class = TimeClass.find(params[:id])
    if @time_class.update(time_class_params)
      flash[:success] = "更新完了"
      redirect_to teachers_time_classes_path
    else
      render :edit
    end
  end

  # def destroy
  # @time_class = timeClass.find(params[:id])
  # @time_class.destroy
  # redirect_to teachers_time_classes_path
  # end

  private

  def time_class_params
    params.require(:time_class).permit(:time_zone)
  end
end

app/controllers/teachers/unlocks_controller.rb
# frozen_string_literal: true

class Teachers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
  end
end

app/helpers/students/lessons_helper.rb
module Students::LessonsHelper
end

app/views/teachers/lessons/edit.html.erb
<div class="container">
	<div class="row">
			<h3>レッスン編集</h3>
			<%= form_for [:teachers,@lesson] do |f| %>
				<% if @lesson.errors.any? %>
					<h4 class="message-error"><%= @lesson.errors.count %> 件のエラーのため内容は保存できません。</h4>
						<ul>
							<% @lesson.errors.full_messages.each do |message| %>
								<li><%= message %></li>
							<% end %>
						</ul>
				<% end %>
				<div class="col-xs-4">
					<h4>画像</h4>
						<%= attachment_image_tag @lesson, :image, :fill, 200, 200, format: 'jpeg' %>
					<%= f.attachment_field :image %>
				</div>
				<div class="col-xs-8">
					<h4>クラス</h4>
					<%= f.collection_select :area_class_id, AreaClass.all, :id, :name, :include_blank => "選択して下さい" %>
					<h4>ジャンル</h4>
					<%= f.collection_select :genre_id, Genre.all, :id, :name, :include_blank => "選択して下さい" %>
					<h4>時間帯</h4>
					<%= f.collection_select :time_class_id, TimeClass.all, :id, :time_zone, :include_blank => "選択して下さい" %>
					<h4>担当者</h4>
					<p><%= f.collection_select :teacher_id, Teacher.all, :id, :last_name, :include_blank => "選択して下さい" %></p>
					<%= f.submit '編集を保存する', class: "btn btn-primary" %>
					<%= link_to "戻る", teachers_lessons_path, class: "btn btn-primary" %>
				</div>
			<% end %>
	</div>
</div>

app/views/teachers/lessons/index.html.erb
<div class="container">
	<h3>レッスン一覧</h3>
	<%= link_to "レッスン作成", new_teachers_lesson_path %>
	<% if flash[:success] %>
  		<p class="alert alert-success" role="alert"><%= flash[:success] %></p>
	<% end %>
	<div class="row">
		<table class="table table-striped">
			<thead>
				<th>画像</th>
				<th>クラス名</th>
				<th>ジャンル</th>
				<th>時間帯</th>
				<th>担当</th>
			</thead>
			<tbody>
				<% @lessons.each do |lesson| %>
					<tr>
						<td><%= attachment_image_tag lesson, :image, format: 'jpeg', size: "100x100" %></td>
						<td><%= lesson.area_class&.name %></td>
						<td><%= lesson.genre&.name %></td>
						<td><%= lesson.time_class&.time_zone %></td>
						<td><%= lesson.teacher&.last_name %></td>
						<td><%= link_to "編集する", edit_teachers_lesson_path(lesson.id), class: "btn btn-primary"%></td>
						<td><%= link_to "休講情報入力", teachers_lesson_path(lesson.id), class: "btn btn-danger" %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/teachers/lessons/new.html.erb
<div class="container">
	<div class="row">
			<h3>レッスン新規登録</h3>
			<%= form_for [:teachers,@lesson] do |f| %>
				<% if @lesson.errors.any? %>
					<h4 class="message-error"><%= @lesson.errors.count %> 件のエラーのため内容は保存できません。</h4>
						<ul>
							<% @lesson.errors.full_messages.each do |message| %>
								<li><%= message %></li>
							<% end %>
						</ul>
				<% end %>
				<div class="col-xs-3">
					<h4>画像</h4>
					<%= f.attachment_field :image %>
				</div>
				<div class="col-xs-9">
					<h4>クラス</h4>
					<%= f.collection_select :area_class_id, AreaClass.all, :id, :name, :include_blank => "選択して下さい" %>
					<h4>ジャンル</h4>
					<%= f.collection_select :genre_id, Genre.all, :id, :name, :include_blank => "選択して下さい" %>
					<h4>時間帯</h4>
					<%= f.collection_select :time_class_id, TimeClass.all, :id, :time_zone, :include_blank => "選択して下さい" %>
					<h4>担当者</h4>
					<p><%= f.collection_select :teacher_id, Teacher.all, :id, :last_name, :include_blank => "選択して下さい" %></p>
					<%= f.submit '新規登録', class: "btn btn-primary" %>
					<%= link_to "戻る", teachers_lessons_path, class: "btn btn-primary" %>

				</div>
			<% end %>
	</div>
</div>

app/views/teachers/lessons/show.html.erb
<div class="container">
	<h3>休講情報入力画面</h3>
	<div class="row">
		<table class="table table-striped">
			<thead>
				<th>クラス名</th>
				<th>ジャンル</th>
				<th>時間帯</th>
				<th>担当</th>
				<th>日付</th>
			</thead>
			<tbody>
					<tr>
						<td><%= attachment_image_tag @lesson, :image, format: 'jpeg', size: "100x100" %></td>
						<td><%= @lesson.area_class&.name %></td>
						<td><%= @lesson.genre&.name %></td>
						<td><%= @lesson.time_class&.time_zone %></td>
						<td><%= @lesson.teacher&.last_name %></td>
					</tr>
			</tbody>
		</table>
		<%= form_for @no_lesson, url: teachers_no_lessons_path do |f| %>
			<%= f.hidden_field :lesson_id, value: @lesson.id %>
			<p><%= f.date_select :no_lesson_date, :use_month_numbers => true %></p>
		    <%= f.submit "休講登録", class: "btn btn-primary"  %>
		    <%= link_to "戻る", teachers_lessons_path, class: "btn btn-primary" %>
    	<% end %>
	</div>
</div>