config/routes.rb
Rails.application.routes.draw do
  root 'students/lessons#index'
  devise_for :teachers, controllers: {
    sessions: 'teachers/sessions',
    passwords: 'teachers/passwords',
    registrations: 'teachers/registrations',
  }

  devise_scope :teacher do
    post 'teachers/guest_sign_in', to: 'teachers/sessions#new_guest'
  end

  namespace :teachers do
    resources :lessons, only: [:index, :new, :show, :edit, :create, :update]
    resources :area_classes, only: [:index, :create, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :courses, only: [:index, :create, :edit, :update, :destroy]
    resources :time_classes, only: [:index, :create, :edit, :update, :destroy]
    resources :attendees, only: [:create, :destroy, :index, :edit, :update]
    resources :students, only: [:index, :show, :edit, :update]
    resources :no_lessons, only: [:index, :create, :destroy]
    # get 'search/' => 'search#search', as: 'search'
  end
  get 'teachers/index'

  devise_for :students, controllers: {
    sessions: 'students/sessions',
    passwords: 'students/passwords',
    registrations: 'students/registrations',
  }

  devise_scope :student do
    post 'students/guest_sign_in', to: 'students/sessions#new_guest'
  end

  namespace :students do
    resources :lessons, only: [:index, :show]
    resources :attendees, only: [:index, :show, :create]
    resources :requests, only: [:show, :create]
  end
  resources :students, only: [:show, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :course, optional: true
  belongs_to :teacher, optional: true
  has_many :attendees, dependent: :destroy

  validates :last_name, presence: true
  validates :sub_last_name, presence: true
  validates :first_name, presence: true
  validates :sub_first_name, presence: true
  validates :email, presence: true

  def self.guest
    find_or_create_by!(last_name: '生徒', first_name: '花子', sub_last_name: 'セイト', sub_first_name: 'ハナコ', email: 'guest_student@example.com') do |student|
      student.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
end

app/controllers/students/attendees_controller.rb
class Students::AttendeesController < ApplicationController
  before_action :authenticate_student!

  def index
    @attendees = current_student.attendees.where(attendance_date: Time.now.beginning_of_year..Time.now.end_of_year, attendance_status:'承認')
  end

  def show
    @attendee = current_student.attendees.last
  end

  def create
    @attendee = Attendee.new(attendee_params)
    @attendee.student_id = current_student.id
    # if
      # @attendee.attendance_date == @attendee.attendance_date && @attendee.lesson_id == @attendee.lesson_id
      # flash[:danger] = "承認待ちです"
      # redirect_to students_lesson_path(lesson.id)
    # else
    @attendee.save
    redirect_to students_attendee_path(current_student)
    # end
  end

  private

  def attendee_params
    params.require(:attendee).permit(:student_id, :lesson_id, :attendance_date, :attendance_status)
  end
end

app/controllers/students/confirmations_controller.rb
# frozen_string_literal: true

class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/lessons_controller.rb
class Students::LessonsController < ApplicationController
  def index
    @lessons = Lesson.all
    @no_lessons = NoLesson.all.order(created_at: :desc)
  end

  def show
    @student = current_student
    @lesson = Lesson.find(params[:id])
    @no_lessons = NoLesson.all.order(created_at: :desc)
    @attendee = Attendee.new
  end
end

app/controllers/students/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource)
    students_lessons_path(resource)
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students/requests_controller.rb
class Students::RequestsController < ApplicationController
  before_action :authenticate_student!

  # コース変更依頼画面へ遷移
  def show
    @student = current_student
  end

  # コース変更依頼をActionMailerで送信
  def create
    # @student = current_student
    # @course = params[:student][:course_id]
    ChangeMailer.send_change(current_student, params[:student][:course_id]).deliver
    redirect_to students_request_path(current_student)
    flash[:success] = "変更依頼を送信しました"
  end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  # ログイン後に遷移するpathを設定
  def after_sign_in_path_for(resource)
    students_lessons_path(resource)
  end

  # ログアウト後に遷移するpathを設定
  def after_sign_out_path_for(resource)
    new_student_session_path
  end

  # ゲストユーザー(生徒)ログイン
  def new_guest
    student = Student.guest
    sign_in student
    flash[:notice] = "ゲストユーザー(生徒)としてログインしました。"
    redirect_to root_path
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_student!

  def show
    @student = current_student
    @attendees = @student.attendees.where(attendance_status: "承認")
  end

  def edit
    @student = current_student
  end

  def update
    @student = current_student
    @attendees = @student.attendees
    if @student.update(student_params)
      flash[:success] = "編集内容が保存されました."
      redirect_to student_path
    else
      render :edit
    end
  end

  private

  def student_params
    params.require(:student).permit(:last_name, :first_name, :sub_last_name, :sub_first_name, :email, :course_id)
  end
end

app/controllers/teachers/students_controller.rb
class Teachers::StudentsController < ApplicationController
  before_action :authenticate_teacher!

  def index
    @students = Student.all
  end

  def show
    @student = Student.find_by(id: params[:id])
  end

  # def search
  # Viewのformで取得したパラメータをモデルに渡す
  # @students = Student.search(id: params[:search])
  # end

  def edit
    @student = Student.find_by(id: params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    flash[:success] = "生徒情報更新完了"
    redirect_to teachers_students_path
  end

  private

  def student_params
    params.require(:student).permit(:teacher_id, :course_id)
  end
end

app/helpers/students/attendees_helper.rb
module Students::AttendeesHelper
end

app/helpers/students/lessons_helper.rb
module Students::LessonsHelper
end

app/helpers/students/requests_helper.rb
module Students::RequestsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers/students_helper.rb
module Teachers::StudentsHelper
end

app/views/students/change.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-5">
			<h2>コース変更依頼</h2>
			<!-- , url: students_path -->
				<%= form_for @student, url: {action: 'create'} do |f| %>
					<p class="h5">現在のコース:</p>
					<p class="h3"><%= @student.course.name %></p>
					<p class="h5">変更後のコース:</p>
					<p class="h3"><%= f.collection_select :course_id, Course.all, :id, :name, :include_blank => "選択して下さい" %></p><br>
					<%= f.submit '変更依頼を送信', class: "btn btn-primary"%>
					<p>※コース変更は翌月1日から適用されます。</p>
				<% end %>
		</div>
		<div class="col-xs-5">
			<h4>料金表</h4>
			<table class="table table-striped">
				<thead>
					<th>コース</th>
					<th>料金</th>
					<th>1レッスン単価</th>
				</thead>
				<tbody>
					<tr>
						<td>単発</td>
						<td>2000円<br>(高校生以下1,500円)</td>
						<td></td>
					</tr>
					<tr>
						<td>月2回コース</td>
						<td>4,000円</td>
						<td>(2,000円)</td>
					</tr>
						<td>月4回コース</td>
						<td>6,800円</td>
						<td>(1,700円)</td>
					<tr>
						<td>月6回コース</td>
						<td>9,800円</td>
						<td>(1,633円)</td>
					</tr>
					<tr>
						<td>通い放題</td>
						<td>12,000円</td>
						<td></td>
					</tr>
					<tr>
						<td>子ども月4回コース</td>
						<td>4,000円</td>
						<td>(1,000円)</td>
					</tr>
					<tr>
						<td>子ども通い放題</td>
						<td>7,000円</td>
						<td></td>
					</tr>
				</tbody>
		</table>
		</div>
	</div>
</div>

app/views/students/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-6">
			<h2>マイページ編集</h2>
			<%= form_for @student do |f| %>
				<% if @student.errors.any? %>
					<h4 class="message-error"><%= @student.errors.count %> 件のエラーのため内容は保存できません。</h4>
						<ul>
							<% @student.errors.full_messages.each do |message| %>
								<li><%= message %></li>
							<% end %>
						</ul>
				<% end %>
					<table class="table">
						<tr>
							<th>姓</th>
							<td><%= f.text_field :last_name %></td>
						</tr>
						<tr>
							<th>名</th>
							<td><%= f.text_field :first_name %></td>
						</tr>
						<tr>
							<th>セイ</th>
							<td><%= f.text_field :sub_last_name %></td>
						</tr>
						<tr>
							<th>メイ</th>
							<td><%= f.text_field :sub_first_name %></td>
						</tr>
						<tr>
							<th>メールアドレス</th>
							<td><%= f.text_field :email %></td>
						</tr>
					</table>
					<%= f.submit '変更を保存する', class: "btn btn-success" %>
			<% end %>
			<br>
			<%= link_to "戻る", student_path(current_student),class: "btn btn-primary" %>
		</div>
	</div>
</div>

app/views/students/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-5">
			<h3>生徒マイページ</h3>
				<% if flash[:success] %>
		  			<p class="alert alert-success" role="alert"><%= flash[:success] %></p>
				<% end %>
				<table class="table">
					<tr>
						<th>氏名</th>
						<td><%= @student.last_name %><%= @student.first_name %></td>
					</tr>
					<tr>
						<th>シメイ</th>
						<td><%= @student.sub_last_name %><%= @student.sub_first_name %></td>
					</tr>
					<tr>
						<th>メールアドレス</th>
						<td><%= @student.email %></td>
					</tr>
					<tr>
						<th>コース</th>
						<td><%= @student.course&.name %></td>
					</tr>
				</table>

				<%= link_to "編集",  edit_student_path(@student.id), class: "btn btn-primary" %>
				<%= link_to "出席履歴一覧", students_attendees_path, class: "btn btn-primary" %>
				<%= link_to "コース変更依頼", students_request_path(@student.id), class: "btn btn-danger" %>
		</div>
		<div class="col-xs-3">
			<h3>出席カレンダー</h3>
				<%= month_calendar events: @attendees do |date,attendees| %>
					<%= date.day %>
					<% attendees.each do |attendee| %>
						<%= image_tag 'tigre.png', :size => '40x40' %>
					<% end %>
				<% end %>
		</div>
	</div>
</div>